# Generated by Django 4.2.4 on 2023-09-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_tag_delete_relationship_scope_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Relationship',
        ),
    ]
